.PHONY: all format lint lint-fix tsc build test

all: format lint tsc build test

format:
	npm run format

lint:
	npm run lint

lint-fix:
	npm run lint-fix

tsc:
	npm run tsc

build:
	npm run build

test:
	npm run test
